module.exports = {
    BASEROUTEMSG : "Server has been started successfully",
    EMAILEXISTS : "Profile with this email already exists.",
    EMAILNOTEXISTS: "Profile with entered email address is not registered.",
    INVALIDPASSWORD: "Invalid Password",
    INVALIDJWTTOKEN : "Invalid Token",
    LOGINFAILED: "Login Failed",
    REGISTRATIONFAILED : "Registration Failed",
    STATUSNOTFOUND : 400,
    STATUSNOTAUTHORIZED : 401,
    USERNOTPERMITTED : 403,
    NOTFOUND : 404,
    NOTAUTHORIZEDMSG : "Not authorized",
    NOTAUTHENTICATEMSG : "Not authenticate",
    INTERNALERRORSTATUS : 500,
    STATUSOK: 200,
    STATUSCREATED : 201,
    HASHALGO: "sha256",
    HASHENCODING: "hex",
    CRYPTOBYES : 20,
    MINUTES: 20,
    SECONDS: 60,
    MILLISECONDS: 1000,
    EMAILSUBJECT: "Helping-Hand Portal Password reset token",
    EMAILBODY : "Use the below password reset token to set a new password. \n\n ",
    RESETEMAILSENT : "Password reset link sent successfully on your email address.",
    RESETEMAILERROR: "Error occurred while sending password reset email.",
    REMOVEUSERCOLUMNPASSWORD : "-password",
};