name: Terraform Setup for Azure

on:
  workflow_dispatch:
    description: "Trigger workflow to set up Azure environment with Terraform"

jobs:
  setup:
    name: Set Up Azure Environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2
        terraform_wrapper: false

    - name: Authenticate to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Up SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub

    - name: Extract Public Key
      id: ssh-key
      run: echo "public_key=$(cat ~/.ssh/id_rsa.pub)" >> $GITHUB_ENV

    - name: Extract Azure Credentials
      id: azure-creds
      run: |
        echo "client_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId)" >> $GITHUB_ENV
        echo "client_secret=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret)" >> $GITHUB_ENV
        echo "tenant_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .tenantId)" >> $GITHUB_ENV
        echo "subscription_id=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)" >> $GITHUB_ENV

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Apply Terraform Plan
      run: terraform apply -var="subscription_id=${{ env.subscription_id }}" -var="client_id=${{ env.client_id }}" -var="client_secret=${{ env.client_secret }}" -var="tenant_id=${{ env.tenant_id }}" -var="public_key=${{ env.public_key }}" -auto-approve
      working-directory: terraform

