- name: Set GitHub Secrets for ACR Credentials and VM IP
  uses: actions/github-script@v6
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const secrets = {
        ACR_USERNAME: process.env.acr_username,
        ACR_PASSWORD: process.env.acr_password,
        VM_PUBLIC_IP: process.env.vm_ip
      };
      for (const [key, value] of Object.entries(secrets)) {
        await github.rest.actions.createOrUpdateRepoSecret({
          owner: context.repo.owner,
          repo: context.repo.repo,
          secret_name: key,
          encrypted_value: value
        });
      }

